version: "3.9"

services:
  app:
    container_name: app
    build:
      args:
        - PYTHON_VERSION=3.10
      dockerfile: Dockerfile
      target: run
    networks:
      - uniplanner-dev

  postgres-db:
    container_name: db
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - uniplanner-dev

volumes:
  db-store:


networks:
  uniplanner-dev:
    driver: bridge
    internal: false
    name: uniplanner-dev
